name: Pyanodon Tests

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  genereate_matrix:
    name: "Generate strategy matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyanodontests"
          token: ${{ secrets.token }}
      - id: set-matrix
        run: cat <(echo -n "::set-output name=matrix::") <(jq -c <mod-sets.json)
  run_tests:
    name: ${{ matrix.name }}
    needs: genereate_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{fromJSON(needs.genereate_matrix.outputs.matrix)}}
    steps:
      - name: "Checkout pyanodontests"
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyanodontests"
          token: ${{ secrets.token }}
      - name: "Checkout stdlib"
        uses: actions/checkout@v2
        with:
          repository: "Afforess/Factorio-Stdlib"
          ref: v1.4.6
          path: "factorio/mods/stdlib"
      - name: "Checkout pycoalprocessing"
        if: ${{ matrix.pycoalprocessing }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pycoalprocessing"
          path: "factorio/mods/pycoalprocessing"
          token: ${{ secrets.token }}
      - name: "Checkout pycoalprocessinggraphics"
        if: ${{ matrix.pycoalprocessing }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pycoalprocessinggraphics"
          path: "factorio/mods/pycoalprocessinggraphics"
          token: ${{ secrets.token }}
      - name: "Checkout pyindustry"
        if: ${{ matrix.pyindustry }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyindustry"
          path: "factorio/mods/pyindustry"
          token: ${{ secrets.token }}
      - name: "Checkout pyfusionenergy"
        if: ${{ matrix.pyfusionenergy }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyfusionenergy"
          path: "factorio/mods/pyfusionenergy"
          token: ${{ secrets.token }}
      - name: "Checkout pyfusionenergygraphics"
        if: ${{ matrix.pyfusionenergy }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyfusionenergygraphics"
          path: "factorio/mods/pyfusionenergygraphics"
          token: ${{ secrets.token }}
      - name: "Checkout pyhightech"
        if: ${{ matrix.pyhightech }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyhightech"
          path: "factorio/mods/pyhightech"
          token: ${{ secrets.token }}
      - name: "Checkout pyhightechgraphics"
        if: ${{ matrix.pyhightech }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyhightechgraphics"
          path: "factorio/mods/pyhightechgraphics"
          token: ${{ secrets.token }}
      - name: "Checkout pyrawores"
        if: ${{ matrix.pyrawores }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyrawores"
          path: "factorio/mods/pyrawores"
          token: ${{ secrets.token }}
      - name: "Checkout pyraworesgraphics"
        if: ${{ matrix.pyrawores }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyraworesgraphics"
          path: "factorio/mods/pyraworesgraphics"
          token: ${{ secrets.token }}
      - name: "Checkout pypetroleumhandling"
        if: ${{ matrix.pypetroleumhandling }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pypetroleumhandling"
          path: "factorio/mods/pypetroleumhandling"
          token: ${{ secrets.token }}
      - name: "Checkout pypetroleumhandlinggraphics"
        if: ${{ matrix.pypetroleumhandling }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pypetroleumhandlinggraphics"
          path: "factorio/mods/pypetroleumhandlinggraphics"
          token: ${{ secrets.token }}
      - name: "Checkout pyalienlife"
        if: ${{ matrix.pyalienlife }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyalienlife"
          path: "factorio/mods/pyalienlife"
          token: ${{ secrets.token }}
      - name: "Checkout pyalienlifegraphics1"
        if: ${{ matrix.pyalienlife }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyalienlifegraphics1"
          path: "factorio/mods/pyalienlifegraphics"   #Mod name doesn't have 1 at the end
          token: ${{ secrets.token }}
      - name: "Checkout pyalienlifegraphics2"
        if: ${{ matrix.pyalienlife }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyalienlifegraphics2"
          path: "factorio/mods/pyalienlifegraphics2"   
          token: ${{ secrets.token }}
      - name: "Checkout pyalienlifegraphics3"
        if: ${{ matrix.pyalienlife }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyalienlifegraphics3"
          path: "factorio/mods/pyalienlifegraphics3"   
          token: ${{ secrets.token }}
      - name: "Checkout pyalternativeenergy"
        if: ${{ matrix.pyalternativeenergy }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyalternativeenergy"
          path: "factorio/mods/pyalternativeenergy"   
          token: ${{ secrets.token }}
      - name: "Checkout pyalternativeenergygraphics"
        if: ${{ matrix.pyalternativeenergy }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyalternativeenergygraphics"
          path: "factorio/mods/pyalternativeenergygraphics"   
          token: ${{ secrets.token }}
      - name: "TEST: Load Factorio"
        uses: ShadowGlass0/factorio-docker-for-github-actions@main
