name: Pyanodon Tests

on:
  workflow_call:
    inputs:
      repository:
        type: string
        description: "Caller repository"
        required: false
        default: ""
      ref:
        type: string
        description: "Ref/sha to use for the caller repository"
        required: false
        default: ""
      test_ref:
        type: string
        description: "Ref/sha to use for pyanodontest"
        required: false
        default: "v1"
    secrets:
      token:
        description: "Token for pyanodontestuser"
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.token }}
  EVENT_REPOSITORY: ${{ inputs.repository }}
  EVENT_REF: ${{ inputs.ref }}

jobs:
  genereate_matrix:
    name: "Generate strategy matrix"
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: checkout
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyanodontests"
          token: ${{ secrets.token }}
          ref: ${{ inputs.test_ref }}
      - id: set-matrix
        run: ./getrefs.sh
  run_tests:
    name: ${{ matrix.name }}
    needs: genereate_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.genereate_matrix.outputs.matrix) }}
    steps:
      - name: "Checkout pyanodontests"
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyanodontests"
          token: ${{ secrets.token }}
          ref: ${{ inputs.test_ref }}
      - name: "Checkout stdlib"
        uses: actions/checkout@v2
        with:
          repository: "Afforess/Factorio-Stdlib"
          ref: v1.4.6
          path: "factorio/mods/stdlib"
      - name: "Checkout pycoalprocessing"
        if: ${{ matrix.pycoalprocessing }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pycoalprocessing"
          path: "factorio/mods/pycoalprocessing"
          ref: ${{ matrix.pycoalprocessing }}
          token: ${{ secrets.token }}
      - name: "Checkout pycoalprocessinggraphics"
        if: ${{ matrix.pycoalprocessinggraphics }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pycoalprocessinggraphics"
          path: "factorio/mods/pycoalprocessinggraphics"
          ref: ${{ matrix.pycoalprocessinggraphics }}
          token: ${{ secrets.token }}
      - name: "Checkout pyindustry"
        if: ${{ matrix.pyindustry }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyindustry"
          path: "factorio/mods/pyindustry"
          ref: ${{ matrix.pyindustry }}
          token: ${{ secrets.token }}
      - name: "Checkout pyfusionenergy"
        if: ${{ matrix.pyfusionenergy }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyfusionenergy"
          path: "factorio/mods/pyfusionenergy"
          ref: ${{ matrix.pyfusionenergy }}
          token: ${{ secrets.token }}
      - name: "Checkout pyfusionenergygraphics"
        if: ${{ matrix.pyfusionenergygraphics }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyfusionenergygraphics"
          path: "factorio/mods/pyfusionenergygraphics"
          ref: ${{ matrix.pyfusionenergygraphics }}
          token: ${{ secrets.token }}
      - name: "Checkout pyhightech"
        if: ${{ matrix.pyhightech }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyhightech"
          path: "factorio/mods/pyhightech"
          ref: ${{ matrix.pyhightech }}
          token: ${{ secrets.token }}
      - name: "Checkout pyhightechgraphics"
        if: ${{ matrix.pyhightechgraphics }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyhightechgraphics"
          path: "factorio/mods/pyhightechgraphics"
          ref: ${{ matrix.pyhightechgraphics }}
          token: ${{ secrets.token }}
      - name: "Checkout pyrawores"
        if: ${{ matrix.pyrawores }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyrawores"
          path: "factorio/mods/pyrawores"
          ref: ${{ matrix.pyrawores }}
          token: ${{ secrets.token }}
      - name: "Checkout pyraworesgraphics"
        if: ${{ matrix.pyraworesgraphics }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyraworesgraphics"
          path: "factorio/mods/pyraworesgraphics"
          ref: ${{ matrix.pyraworesgraphics }}
          token: ${{ secrets.token }}
      - name: "Checkout pypetroleumhandling"
        if: ${{ matrix.pypetroleumhandling }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pypetroleumhandling"
          path: "factorio/mods/pypetroleumhandling"
          ref: ${{ matrix.pypetroleumhandling }}
          token: ${{ secrets.token }}
      - name: "Checkout pypetroleumhandlinggraphics"
        if: ${{ matrix.pypetroleumhandlinggraphics }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pypetroleumhandlinggraphics"
          path: "factorio/mods/pypetroleumhandlinggraphics"
          ref: ${{ matrix.pypetroleumhandlinggraphics }}
          token: ${{ secrets.token }}
      - name: "Checkout pyalienlife"
        if: ${{ matrix.pyalienlife }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyalienlife"
          path: "factorio/mods/pyalienlife"
          ref: ${{ matrix.pyalienlife }}
          token: ${{ secrets.token }}
      - name: "Checkout pyalienlifegraphics1"
        if: ${{ matrix.pyalienlifegraphics }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyalienlifegraphics1"
          path: "factorio/mods/pyalienlifegraphics"   #Mod name doesn't have 1 at the end
          ref: ${{ matrix.pyalienlifegraphics }}
          token: ${{ secrets.token }}
      - name: "Checkout pyalienlifegraphics2"
        if: ${{ matrix.pyalienlifegraphics2 }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyalienlifegraphics2"
          path: "factorio/mods/pyalienlifegraphics2"   
          ref: ${{ matrix.pyalienlifegraphics2 }}
          token: ${{ secrets.token }}
      - name: "Checkout pyalienlifegraphics3"
        if: ${{ matrix.pyalienlifegraphics3 }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyalienlifegraphics3"
          path: "factorio/mods/pyalienlifegraphics3"   
          ref: ${{ matrix.pyalienlifegraphics3 }}
          token: ${{ secrets.token }}
      - name: "Checkout pyalternativeenergy"
        if: ${{ matrix.pyalternativeenergy }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyalternativeenergy"
          path: "factorio/mods/pyalternativeenergy"   
          ref: ${{ matrix.pyalternativeenergy }}
          token: ${{ secrets.token }}
      - name: "Checkout pyalternativeenergygraphics"
        if: ${{ matrix.pyalternativeenergygraphics }}
        uses: actions/checkout@v2
        with:
          repository: "pyanodon/pyalternativeenergygraphics"
          path: "factorio/mods/pyalternativeenergygraphics"   
          ref: ${{ matrix.pyalternativeenergygraphics }}
          token: ${{ secrets.token }}
      - name: "TEST: Load Factorio"
        uses: ShadowGlass0/factorio-docker-for-github-actions@main
