---
name: Manual test

on:
  workflow_dispatch:

jobs:
  test0:
    name: Tmp test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run test
        run: python test_getrefs.py
  test1:
    name: Test Full
    uses: pyanodon/pyanodontests/.github/workflows/pytest.yml@main
    with:
      test_ref: main
    secrets: inherit
  # test2:
  #   name: Test PyAl
  #   uses: pyanodon/pyanodontests/.github/workflows/pytest.yml@main
  #   with:
  #     repository: "pyanodon/pyalienlife"
  #     ref: "master"
  #     test_ref: main
  #   secrets: inherit
